import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, Bell, ClipboardCheck, CloudSun, History, Leaf, Menu, UserCircle2, Warehouse, X } from "lucide-react";
import { Link } from "react-router-dom";
import { LogoutButton } from "../../components/auth/LogoutButton";
import { reviewerApi, type ApiReviewerDashboard } from "../../lib/reviewer-api";

function NavItem({ icon: Icon, label, active = false }: { icon: typeof Warehouse; label: string; active?: boolean }) {
  return <button className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left transition-all duration-300 ${active ? "bg-[#1c2a13] text-white shadow-md" : "text-[#44483f] hover:bg-[#edf4dc]"}`}><Icon size={18} strokeWidth={active ? 2.5 : 1.8}/><span className={active ? "font-display text-sm font-bold" : "text-sm font-semibold"}>{label}</span></button>;
}

const elapsed = (value: string) => {
  const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000));
  if (minutes < 1) return "baru saja";
  if (minutes < 60) return `${minutes} menit lalu`;
  const hours = Math.floor(minutes / 60);
  return hours < 24 ? `${hours} jam lalu` : `${Math.floor(hours / 24)} hari lalu`;
};

export function ReviewListPage() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [isLoaded, setIsLoaded] = useState(false);
  const [activeFilter, setActiveFilter] = useState("semua");
  const [data, setData] = useState<ApiReviewerDashboard | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    const timer = window.setTimeout(() => setIsLoaded(true), 50);
    reviewerApi.getDashboard().then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Review gagal dimuat"));
    return () => window.clearTimeout(timer);
  }, []);
  const pending = activeFilter === "selesai" ? [] : data?.pending_reviews ?? [];

  return <div className="min-h-screen min-w-[300px] bg-[#f3f3ec] text-[#15240a] font-sans overflow-hidden flex">
    {mobileNavOpen && <div className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm transition-opacity duration-300 md:hidden" onClick={() => setMobileNavOpen(false)}/>}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col justify-between bg-[#fafaf6] p-5 shadow-sm transition-transform duration-300 ${mobileNavOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0"}`}>
      <div><div className="mb-8 flex items-center justify-between px-2"><div className="flex items-center gap-2 rounded-xl bg-[#15240a]/80 px-3 py-2 text-[10px] font-bold tracking-[0.16em] text-white"><Leaf size={15} className="text-[#85c254]"/> REMBUKTANI</div><button className="md:hidden text-[#44483f] hover:text-[#15240a] transition-colors" onClick={() => setMobileNavOpen(false)} aria-label="Tutup menu"><X size={20}/></button></div><nav className="space-y-1"><Link to="/reviewer/dashboard"><NavItem icon={Warehouse} label="Beranda"/></Link><Link to="/reviewer/review"><NavItem active icon={ClipboardCheck} label="Review Masuk"/></Link><Link to="/reviewer/history"><NavItem icon={History} label="Riwayat"/></Link><Link to="/reviewer/profile"><NavItem icon={UserCircle2} label="Profil"/></Link></nav></div>
      <div className="mt-auto space-y-4"><div className="flex items-center gap-3 rounded-xl bg-[#e9fcb5] p-3 text-xs"><span className="size-2.5 rounded-full bg-[#85c254] shrink-0"/><div><p className="font-bold text-[#15240a]">Sinkronisasi BMKG</p><p className="text-[10px] text-[#56652e]">{data?.weather ? `${data.weather.condition} ${data.weather.temp}°C` : "Belum ada bukti cuaca"}</p></div></div><div className="flex items-center justify-between px-1"><div className="flex items-center gap-2"><div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-[#0d1b03] text-white"><UserCircle2 size={15}/></div><div><p className="max-w-[100px] truncate text-xs font-bold text-[#15240a]">{data?.reviewer_name ?? "Reviewer"}</p><p className="text-[10px] text-[#666a60]">Reviewer</p></div></div><LogoutButton compact/></div></div>
    </aside>
    <div className="flex-1 flex flex-col min-w-0 md:ml-[260px]">
      <header className="fixed top-0 left-0 right-0 md:left-[260px] z-30 flex h-14 shrink-0 items-center justify-between bg-[#f3f3ec]/90 px-4 backdrop-blur-md sm:px-6 lg:px-8 border-b border-[#deded4]/40"><div className="flex items-center gap-3"><button className="rounded-md p-1.5 transition-colors hover:bg-black/5 md:hidden" onClick={() => setMobileNavOpen(true)}><Menu size={20}/></button><span className="truncate rounded bg-[#e9fcb5] px-2.5 py-1 text-[10px] font-bold text-[#213014] sm:text-xs">Wilayah: {data?.region ?? "Belum ada wilayah"}</span></div><div className="flex items-center gap-3 sm:gap-5"><span className="hidden items-center gap-1.5 text-xs font-medium text-[#44483f] sm:flex"><CloudSun size={16}/>{data?.weather ? `${data.weather.condition} ${data.weather.temp}°C` : "Cuaca belum tersedia"}</span><Bell size={18} className="cursor-pointer text-[#44483f] transition hover:text-[#15240a]"/><div className="flex size-7 cursor-pointer items-center justify-center rounded-full bg-[#0d1b03] text-white"><UserCircle2 size={14}/></div></div></header>
      <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-5xl pt-14">
        <div className={`mb-6 transition-all duration-700 ease-out ${isLoaded ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-4"}`}><h1 className="text-2xl sm:text-3xl lg:text-4xl font-display font-bold leading-tight text-[#15240a]">Review Masuk</h1><p className="mt-2 text-xs sm:text-sm text-[#44483f] leading-relaxed max-w-2xl">Tinjau kondisi lahan dan berikan pertimbangan sebelum petani mengambil keputusan.</p></div>
        <div className={`mb-8 flex flex-wrap items-center gap-2 sm:gap-3 transition-all delay-100 duration-700 ease-out ${isLoaded ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}><button onClick={() => setActiveFilter("semua")} className={`rounded-full px-4 py-2 text-[10px] sm:text-xs font-bold transition-all ${activeFilter === "semua" ? "bg-[#15240a] text-white shadow-md" : "bg-white border border-[#deded4] text-[#44483f] hover:bg-[#fafaf6]"}`}>Semua ({(data?.pending_reviews.length ?? 0) + (data?.completed_reviews.length ?? 0)})</button><button onClick={() => setActiveFilter("menunggu")} className={`flex items-center gap-1.5 rounded-full px-4 py-2 text-[10px] sm:text-xs font-bold transition-all ${activeFilter === "menunggu" ? "bg-[#15240a] text-white shadow-md" : "bg-white border border-[#deded4] text-[#44483f] hover:bg-[#fafaf6]"}`}><span className={`size-1.5 rounded-full ${activeFilter === "menunggu" ? "bg-white" : "bg-[#ca8a04]"}`}/>Menunggu Pertimbangan ({data?.pending_reviews.length ?? 0})</button><button onClick={() => setActiveFilter("selesai")} className={`rounded-full px-4 py-2 text-[10px] sm:text-xs font-bold transition-all ${activeFilter === "selesai" ? "bg-[#15240a] text-white shadow-md" : "bg-white border border-[#deded4] text-[#44483f] hover:bg-[#fafaf6]"}`}>Sudah Diberi Masukan ({data?.completed_reviews.length ?? 0})</button></div>
        {error && <div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-xs font-semibold text-red-700">{error}</div>}
        <div className="space-y-4 sm:space-y-5">{pending.map((review, index) => <div key={review.case_id} className={`group rounded-2xl bg-white p-5 sm:p-6 shadow-sm border border-[#deded4]/60 transition-all hover:border-[#85c254]/50 hover:shadow-md duration-700 ease-out ${isLoaded ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"}`} style={{ transitionDelay: `${200 + index * 100}ms` }}><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div className="flex-1"><div className="flex flex-wrap items-center gap-2 text-[10px] sm:text-xs mb-3"><span className="rounded bg-[#e9fcb5] px-2 py-1 font-bold text-[#213014]">{review.land_name} • {review.crop_name}</span><span className="text-[#666a60]">{review.growth_stage}</span></div><p className="text-[10px] sm:text-xs text-[#a4a99d] mb-1.5">Pemilik: <span className="font-semibold text-[#666a60]">{review.farmer_name} ({review.location})</span></p><h3 className="text-sm sm:text-base font-bold text-[#15240a] mb-4 leading-snug">{review.assessment?.summary ?? `Pertimbangan ${review.decision_type}`}</h3><div className="flex flex-wrap items-center gap-2">{review.evidence.bmkg && <span className="flex items-center gap-1.5 rounded-lg bg-[#fafaf6] border border-[#deded4]/50 px-2.5 py-1.5 text-[9px] sm:text-[10px] text-[#44483f]"><CloudSun size={12} className="text-[#666a60]"/> BMKG: {review.evidence.bmkg.text}</span>}{review.evidence.field_pulse && <span className="flex items-center gap-1.5 rounded-lg bg-[#fff1f2] border border-[#fecdd3]/50 px-2.5 py-1.5 text-[9px] sm:text-[10px] text-[#9f1239]"><AlertTriangle size={12} className="text-[#e11d48]"/> Kondisi Lapangan: {review.evidence.field_pulse.text}</span>}<span className="text-[9px] sm:text-[10px] text-[#a4a99d]">• Diajukan {elapsed(review.submitted_at)}</span></div></div><div className="flex flex-row md:flex-col items-center md:items-end justify-between md:justify-start gap-4 border-t md:border-t-0 border-[#deded4]/50 pt-4 md:pt-0 shrink-0"><div className="inline-flex items-center gap-1.5 rounded-full bg-[#fef08a]/40 px-2.5 py-1 text-[9px] sm:text-[10px] font-bold text-[#a16207]"><span className="size-1.5 rounded-full bg-[#ca8a04]"/> Menunggu Pertimbangan</div><Link to={`/reviewer/review/${review.case_id}`} className="flex items-center justify-center gap-1.5 rounded-xl bg-[#85c254] px-5 py-2.5 text-xs font-bold text-[#15240a] transition-colors hover:bg-[#98cf6a]">Lihat Review <ArrowRight size={14} className="transition-transform group-hover:translate-x-1"/></Link></div></div></div>)}{!error && data && pending.length === 0 && <div className="rounded-2xl border border-[#deded4]/60 bg-white p-8 text-center text-sm text-[#666a60]">{activeFilter === "selesai" ? "Review selesai tersedia di halaman Riwayat." : "Belum ada review yang menunggu pertimbangan."}</div>}</div><div className="h-10"/>
      </div></main>
    </div>
  </div>;
}
