import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, Bell, CheckCircle2, ChevronRight, History, Leaf, Menu, Sprout, UserCircle2, Users, Warehouse, X } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { ensureAssessment, saveWorkflow, type WorkflowData } from "../../lib/decision-workflow";
import { ErrorCard, LoadingCard } from "../../components/farmer/WorkflowLayout";
import { getUser } from "../../lib/auth";
import { LogoutButton } from "../../components/auth/LogoutButton";
import { WeatherStatus } from "../../components/farmer/WeatherStatus";

const splitRationale = (rationale?: string) => (rationale || "Berdasarkan kondisi lapangan dan data cuaca yang tersimpan.").split(/[.;]|\s+·\s+/).map((item) => item.trim()).filter(Boolean).slice(0, 3);

export function ActionAlternativesPage() {
  const { landId = "" } = useParams();
  const navigate = useNavigate();
  const user = getUser();
  const [data, setData] = useState<WorkflowData>();
  const [error, setError] = useState("");
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  useEffect(() => { if (landId) ensureAssessment(landId).then(setData).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Opsi gagal dimuat")); }, [landId]);
  const choose = (id: string) => { const option = data?.result.options.find((item) => item.id === id); if (!option) return; saveWorkflow(landId, { option_id: option.id, option_title: option.title, option_description: option.description || "", option_rationale: option.rationale || "" }); navigate(`/farmer/lands/${landId}/optional-review`); };

  return <div className="min-h-screen bg-[#f3f3ec] text-[#15240a]">
    {mobileNavOpen && <button className="fixed inset-0 z-30 bg-black/30 md:hidden" onClick={() => setMobileNavOpen(false)} aria-label="Tutup menu" />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col justify-between bg-[#fafaf6] p-5 shadow-sm transition-transform duration-300 ${mobileNavOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0"}`}><div><div className="mb-6 flex items-center justify-between px-2"><div className="flex items-center gap-2 rounded-xl bg-[#15240a]/80 px-3 py-2 text-[10px] font-bold tracking-[0.16em] text-white"><Leaf size={15} className="text-[#85c254]"/>REMBUKTANI</div><button className="md:hidden" onClick={() => setMobileNavOpen(false)} aria-label="Tutup menu"><X size={20}/></button></div><a href="/farmer/lands/new" className="mb-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#85c254] px-4 py-3 text-sm font-semibold">+ Tambah Lahan</a><nav className="space-y-1"><SideLink to="/farmer/dashboard" icon={<Warehouse size={18}/>} label="Beranda"/><SideLink to="/farmer/lands" icon={<Sprout size={18}/>} label="Lahan" active/><SideLink to="/farmer/history" icon={<History size={18}/>} label="Riwayat"/><SideLink to="/farmer/profile" icon={<UserCircle2 size={18}/>} label="Profil"/></nav></div><div className="space-y-4 px-1"><div className="rounded-xl bg-[#e9fcb5] p-3"><p className="mb-2 text-xs font-bold">Sinkronisasi BMKG</p><WeatherStatus preferredLandId={landId}/></div><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-[#0d1b03] text-white"><UserCircle2 size={15}/></div><div><p className="max-w-36 truncate text-xs font-bold">{user?.display_name || user?.displayName || "Sahabat Tani"}</p><p className="text-xs text-[#44483f]">Petani</p></div></div><LogoutButton compact/></div></div></aside>
    <div className="md:pl-[260px]"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#deded4]/60 bg-[#fafaf6]/90 px-4 shadow-sm backdrop-blur-xl sm:px-8"><button className="md:hidden" onClick={() => setMobileNavOpen(true)} aria-label="Buka menu"><Menu size={22}/></button><span className="max-w-[55%] truncate rounded bg-[#e4f6b0] px-2 py-1 text-xs font-semibold">Wilayah: {data ? [data.land.village, data.land.regency].filter(Boolean).join(", ") : "Memuat wilayah"}</span><div className="flex items-center gap-3"><span className="hidden sm:flex"><WeatherStatus preferredLandId={landId}/></span><Bell size={17}/><UserCircle2 size={20}/></div></header>
      <main className="mx-auto max-w-[1180px] px-4 pb-12 pt-7 sm:px-8"><div className="mb-5 flex items-center gap-2 text-xs text-[#56652e]"><span>Lahan</span><ChevronRight size={13}/><span>{data?.land.name || "Memuat lahan"}</span><ChevronRight size={13}/><b>Alternatif Tindakan</b></div><div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="font-display text-3xl font-bold sm:text-4xl">Apa yang ingin Anda lakukan?</h1><p className="mt-2 max-w-2xl text-sm text-[#666a60]">Pilih opsi yang paling sesuai dengan tenaga kerja dan ketersediaan sarana di sawah Anda saat ini.</p></div>{data&&<span className="hidden rounded-full bg-[#def0ab] px-3 py-2 text-xs font-bold md:block">● {data.land.name} · {data.crop.crop_name}</span>}</div>{error?<ErrorCard message={error}/>:!data?<LoadingCard/>:data.result.options.length===0?<ErrorCard message="Ruleset tidak menghasilkan alternatif. Kembali dan lengkapi bukti lapangan."/>:<><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.result.options.map((option,index)=><OptionCard key={option.id} index={index} title={option.title} description={option.description} rationale={option.rationale} onChoose={()=>choose(option.id)}/>)}</div><div className="mt-7 text-center"><button type="button" onClick={()=>navigate(`/farmer/lands/${landId}/final-decision`)} className="inline-flex items-center gap-2 text-sm font-bold text-[#56652e] underline decoration-[#85c254] underline-offset-4">Atau tulis rencana tindakan khusus Anda sendiri <ArrowRight size={15}/></button><p className="mt-4 text-xs text-[#666a60]">Keputusan akhir selalu berada di tangan petani dan pengurus kelompok tani<br className="hidden sm:block"/> berdasarkan kondisi riil di lapangan.</p></div></>}<div className="mt-6 flex items-center justify-center gap-2 text-xs text-[#56652e]"><CheckCircle2 size={15} className="text-[#4f8a45]"/>Pilihan dari AI Gemini/ruleset tersimpan ke sesi sampai keputusan disahkan.</div></main></div>
  </div>;
}

function OptionCard({ index, title, description, rationale, onChoose }: { index: number; title: string; description?: string; rationale?: string; onChoose: () => void }) { const reasons = splitRationale(rationale); return <article className="flex min-h-[470px] flex-col rounded-2xl bg-white p-5 shadow-[0_3px_14px_rgba(21,36,10,0.08)]"><div className="flex items-center justify-between gap-3"><span className="rounded-lg bg-[#e4f6b0] px-3 py-1.5 text-[10px] font-bold text-[#4f8a45]">Opsi {String.fromCharCode(65 + index)} · AI Gemini</span><span className="flex size-8 items-center justify-center rounded-full bg-[#f3f3ec] text-[#56652e]"><Users size={15}/></span></div><h2 className="mt-7 font-display text-2xl font-bold leading-tight">{title}</h2><p className="mt-3 text-sm leading-6 text-[#666a60]">{description || "Tidak ada deskripsi tambahan dari assessment."}</p><div className="my-5 h-px bg-[#deded4]"/><p className="flex items-center gap-2 text-xs font-bold text-[#4f8a45]">♧ Berdasarkan</p><div className="mt-2 rounded-xl bg-[#f3f3ec] p-3 text-xs leading-5 text-[#56652e]">{reasons.map((reason, reasonIndex) => <p key={`${reason}-${reasonIndex}`}>– {reason}</p>)}</div><button onClick={onChoose} className="mt-auto flex items-center justify-center gap-2 rounded-xl bg-[#102606] px-4 py-3 text-xs font-bold text-white">Pilih Alternatif Ini <ArrowRight size={15}/></button></article>; }
function SideLink({ to, icon, label, active = false }: { to: string; icon: ReactNode; label: string; active?: boolean }) { return <a href={to} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${active ? "bg-[#213014] text-white" : "text-[#44483f] hover:bg-[#edf4dc]"}`}>{icon}{label}</a>; }
