import { useEffect, useState, type ReactNode } from "react";
import { Bell, Check, ChevronLeft, CircleHelp, History, Leaf, Menu, Search, Sprout, SunDim, UserCircle2, Warehouse, Waves, X } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { saveWorkflow } from "../../lib/decision-workflow";
import { farmerApi, type ApiCropContext, type ApiLand } from "../../services/farmer-api";
import { getUser } from "../../lib/auth";
import { LogoutButton } from "../../components/auth/LogoutButton";
import { WeatherStatus } from "../../components/farmer/WeatherStatus";

const options = [
  { id: "kering", title: "Lebih Kering", desc: "Air berkurang dibanding sebelumnya. Ketinggian permukaan air surut dan rekahan tanah mulai terlihat di sela rumpun padi.", icon: SunDim },
  { id: "tetap", title: "Tidak Banyak Berubah", desc: "Kondisi air masih relatif sama seperti hari-hari sebelumnya. Ketinggian genangan serta kelembapan lumpur tetap stabil terjaga.", icon: Check },
  { id: "basah", title: "Lebih Basah", desc: "Air bertambah dibanding sebelumnya. Terjadi limpasan baru, volume genangan meningkat, atau saluran irigasi baru dibuka.", icon: Waves },
  { id: "gatau", title: "Tidak Tahu", desc: "Saya belum mengetahui perubahan ketinggian air karena belum sempat turun langsung mengamati petak dalam beberapa hari ini.", icon: CircleHelp },
] as const;

export function ConditionWaterPage() {
  const { landId = "" } = useParams();
  const navigate = useNavigate();
  const user = getUser();
  const [land, setLand] = useState<ApiLand>();
  const [crop, setCrop] = useState<ApiCropContext>();
  const [selected, setSelected] = useState("gatau");
  const [error, setError] = useState("");
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  useEffect(() => { Promise.all([farmerApi.getLand(landId), farmerApi.getActiveCrop(landId)]).then(([nextLand, nextCrop]) => { setLand(nextLand); setCrop(nextCrop); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Konteks gagal dimuat")); }, [landId]);
  const submit = () => { saveWorkflow(landId, { water_trend: selected }); navigate(`/farmer/lands/${landId}/summary`); };

  return <div className="min-h-screen bg-[#f3f3ec] text-[#15240a]">
    {mobileNavOpen && <button className="fixed inset-0 z-30 bg-black/30 md:hidden" onClick={() => setMobileNavOpen(false)} aria-label="Tutup menu" />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col justify-between bg-[#fafaf6] p-5 shadow-sm transition-transform duration-300 ${mobileNavOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0"}`}><div><div className="mb-6 flex items-center justify-between px-2"><div className="flex items-center gap-2 rounded-xl bg-[#15240a]/80 px-3 py-2 text-[10px] font-bold tracking-[0.16em] text-white"><Leaf size={15} className="text-[#85c254]"/>REMBUKTANI</div><button className="md:hidden" onClick={() => setMobileNavOpen(false)} aria-label="Tutup menu"><X size={20}/></button></div><Link to="/farmer/lands/new" className="mb-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#85c254] px-4 py-3 text-sm font-semibold">+ Tambah Lahan</Link><nav className="space-y-1"><SideLink to="/farmer/dashboard" icon={<Warehouse size={18}/>} label="Beranda"/><SideLink to="/farmer/lands" icon={<Sprout size={18}/>} label="Lahan" active/><SideLink to="/farmer/history" icon={<History size={18}/>} label="Riwayat"/><SideLink to="/farmer/profile" icon={<UserCircle2 size={18}/>} label="Profil"/></nav></div><div className="space-y-4 px-1"><div className="rounded-xl bg-[#e9fcb5] p-3"><p className="mb-2 text-xs font-bold">Sinkronisasi BMKG</p><WeatherStatus preferredLandId={landId}/></div><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-[#0d1b03] text-white"><UserCircle2 size={15}/></div><div><p className="max-w-36 truncate text-xs font-bold">{user?.display_name || user?.displayName || "Sahabat Tani"}</p><p className="text-xs text-[#44483f]">Petani</p></div></div><LogoutButton compact/></div></div></aside>
    <div className="md:pl-[260px]"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#deded4]/60 bg-[#fafaf6]/90 px-4 shadow-sm backdrop-blur-xl sm:px-8"><button className="md:hidden" onClick={() => setMobileNavOpen(true)} aria-label="Buka menu"><Menu size={22}/></button><span className="max-w-[55%] truncate rounded bg-[#e4f6b0] px-2 py-1 text-xs font-semibold">Wilayah: {land ? [land.village, land.regency].filter(Boolean).join(", ") : "Memuat wilayah"}</span><div className="flex items-center gap-3"><span className="hidden sm:flex"><WeatherStatus preferredLandId={landId}/></span><Bell size={17}/><UserCircle2 size={20}/></div></header>
      <main className="mx-auto max-w-[900px] px-4 pb-12 pt-7 sm:px-8"><div className="mb-5 flex items-center justify-between gap-4"><Link to={`/farmer/lands/${landId}/irrigation`} className="flex items-center gap-2 text-sm font-semibold text-[#56652e]"><ChevronLeft size={15}/>Kembali</Link><span className="rounded-full bg-white px-3 py-1.5 text-[10px] font-bold">Pertanyaan 3 dari 3 Pertanyaan</span></div><div className="mb-6 h-1.5 overflow-hidden rounded-full bg-[#deded4]"><motion.div initial={{ width: 0 }} animate={{ width: "100%" }} className="h-full rounded-full bg-[#85c254]"/></div>{error?<div className="rounded-2xl bg-[#fff3df] p-4 text-sm">{error}</div>:!land||!crop?<div className="h-80 animate-pulse rounded-2xl bg-white"/>:<><div className="mb-4 flex w-fit items-center gap-2 rounded-lg bg-[#def0ab] px-3 py-1.5 text-xs font-bold"><span className="text-[#4f8a45]">●</span>{land.name} · {crop.crop_name}{crop.variety_name?` ${crop.variety_name}`:""}</div><section className="mb-6"><h1 className="font-display text-3xl font-bold leading-tight sm:text-4xl">Bagaimana perubahan kondisi air dibanding beberapa hari sebelumnya?</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#666a60]">Pilih kondisi yang paling menggambarkan keadaan genangan atau kelembapan di petak sawah Anda selama beberapa hari terakhir.</p></section><div className="space-y-2.5">{options.map((option,index)=>{const Icon=option.icon;return <motion.button key={option.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.04}} onClick={()=>setSelected(option.id)} className={`flex w-full items-start gap-3 rounded-2xl border p-4 text-left transition sm:p-5 ${selected===option.id?"border-[#9fca52] bg-[#e2f9a9] shadow-[0_3px_10px_rgba(133,194,84,0.2)]":"border-transparent bg-white hover:border-[#c8df9c]"}`}><span className={`mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full ${selected===option.id?"bg-[#15240a] text-white":"bg-[#e4f6b0] text-[#56652e]"}`}>{selected===option.id?<Check size={12}/>:<Icon size={14}/>}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-bold">{option.title}{selected===option.id&&<small className="rounded bg-[#c7e27f] px-2 py-0.5 text-[9px] font-bold">TERPILIH</small>}</span><span className="mt-1 block text-xs leading-5 text-[#56652e]">{option.desc}</span></span><span className="text-xs text-[#4f8a45]">{selected===option.id?"◉":"⁙"}</span></motion.button>})}</div><div className="mt-8 flex items-center justify-between gap-4"><button type="button" onClick={()=>navigate(`/farmer/lands/${landId}`)} className="text-xs font-bold text-[#56652e]">Lewati Pertanyaan Ini</button><button onClick={submit} className="flex items-center gap-2 rounded-xl bg-[#15240a] px-5 py-3 text-sm font-bold text-white shadow-[0_5px_12px_rgba(21,36,10,0.2)]">Analisis <Search size={16}/></button></div></>}</main></div></div>;
}
function SideLink({to,icon,label,active=false}:{to:string;icon:ReactNode;label:string;active?:boolean}){return <Link to={to} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${active?"bg-[#213014] text-white":"text-[#44483f] hover:bg-[#edf4dc]"}`}>{icon}{label}</Link>}
